<a href="https://colab.research.google.com/github/shimabang/PyTorch/blob/main/Pytorch_Fundamentals1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Fundamentals**

In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.1+cu116


In [3]:
## Introduction to Tensors
# Create tensors

In [4]:
scalar=torch.tensor(10)

In [5]:
scalar

tensor(10)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

10

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
matrix = torch.tensor([[7, 8], [10, 12]])
matrix

tensor([[ 7,  8],
        [10, 12]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix[0]

tensor([7, 8])

In [15]:
#tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [5, 6, 7]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [5, 6, 7]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [5, 6, 7]])

### Random tensors
Why random tensors?
 these are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 Starts with random nos -> look at data -> update random nos. -> look at data -> update random nos.

In [19]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9606, 0.3160, 0.6707, 0.4585],
        [0.4209, 0.1760, 0.2762, 0.6830],
        [0.0869, 0.1577, 0.7651, 0.5498]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_tensor[1]

tensor([0.4209, 0.1760, 0.2762, 0.6830])

In [23]:
random_tensor1 = torch.rand(1, 10, 10)
random_tensor1

tensor([[[0.6884, 0.9395, 0.7228, 0.7928, 0.2615, 0.1634, 0.0213, 0.3681,
          0.6302, 0.8418],
         [0.6281, 0.0880, 0.4338, 0.7635, 0.2460, 0.9041, 0.0461, 0.2636,
          0.1089, 0.4660],
         [0.3767, 0.1756, 0.9434, 0.3645, 0.4405, 0.9259, 0.8096, 0.0389,
          0.4390, 0.0791],
         [0.0994, 0.8455, 0.0207, 0.7982, 0.5059, 0.2461, 0.5379, 0.0650,
          0.6442, 0.2086],
         [0.3019, 0.7754, 0.5923, 0.5451, 0.7281, 0.2243, 0.6339, 0.7152,
          0.9733, 0.9948],
         [0.1336, 0.1237, 0.3555, 0.8204, 0.1413, 0.3702, 0.9975, 0.0212,
          0.1706, 0.6544],
         [0.8586, 0.9655, 0.6210, 0.8196, 0.5643, 0.2924, 0.3928, 0.1694,
          0.2043, 0.9270],
         [0.8316, 0.3522, 0.0690, 0.6522, 0.3167, 0.0661, 0.6998, 0.5315,
          0.7401, 0.7831],
         [0.2543, 0.3544, 0.3455, 0.3375, 0.8553, 0.6194, 0.3311, 0.8730,
          0.8989, 0.7486],
         [0.4246, 0.5315, 0.0257, 0.6319, 0.0452, 0.3993, 0.8101, 0.7488,
          0.7947,

In [24]:
random_tensor1.ndim

3

In [25]:
random_tensor1.shape

torch.Size([1, 10, 10])

In [26]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
### zeros and ones
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zeros.dtype

torch.float32

In [29]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
# create a range of tensors and tensors like
# use torch.range
torch.range(1, 10)

<ipython-input-31-8e1501a35a8c>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.arange(1, 10)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten= torch.arange(0, 1000, 78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [38]:
one_to_ten= torch.arange(start=0, end=1000, step=78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [36]:
# create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data types

In [37]:
# tensor datatypes - these are one of the 3 big errors with Pytorch &  deep learning:
#1. Tensors not right datatype
#2. Not right shape
#3. Not on the right device
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [40]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, device = None, requires_grad=False) #dtype= 32-bit, 16 bit, 64 bit floating point # device=cpu, cuda  #requires_grad - whether to track the gradients or not
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)  #torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

Create a tensor
1. to get the right datatype from a tensor, use tensor.dtype
2. to get the shape from tensor, use tensor.shape
3. to get the device from tensor, use tensor.device

In [43]:
some_tensor= torch.rand(3, 4)
some_tensor

tensor([[0.2680, 0.3639, 0.8765, 0.9283],
        [0.4246, 0.4316, 0.3660, 0.4832],
        [0.7939, 0.4729, 0.9906, 0.5983]])

In [45]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.2680, 0.3639, 0.8765, 0.9283],
        [0.4246, 0.4316, 0.3660, 0.4832],
        [0.7939, 0.4729, 0.9906, 0.5983]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


# **Manupulating Tensors- Operations on Tensors**
NN comprise of lots of tensors which requires these operations on them.

Operations include:
*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*  Matrix multiplication





In [46]:
#Create a tensor and add 100 to it, multiply by 10
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [47]:
tensor * 10

tensor([10, 20, 30])

In [48]:
tensor - 10

tensor([-9, -8, -7])

In [49]:
# try out built-in functions
torch.mul(tensor, 7)

tensor([ 7, 14, 21])

In [50]:
torch.add(tensor, 10) # try more 

tensor([11, 12, 13])

**Matrix multiplication**

Two main ways of performing multiplication in NNs and Deep learning:

Element-wise multiplication

Matrix multiplication (dot product)

In [51]:
tensor * tensor # element-wise

tensor([1, 4, 9])

In [52]:
print(tensor, "*", tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [53]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
# check for execution time
 %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.15 ms, sys: 963 µs, total: 3.11 ms
Wall time: 3.36 ms


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 464 µs, sys: 54 µs, total: 518 µs
Wall time: 417 µs


tensor(14)